//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class bottle
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public bottle()
    {
        this.bottleOfBranch = new HashSet<bottleOfBranch>();
    }

    public int Id { get; set; }
    public string name { get; set; }
    public Nullable<int> price { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<bottleOfBranch> bottleOfBranch { get; set; }
}

public partial class bottleOfBranch
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public bottleOfBranch()
    {
        this.pay_process = new HashSet<pay_process>();
    }

    public int Id { get; set; }
    public string CountOfBottle { get; set; }
    public Nullable<int> bottleId { get; set; }
    public Nullable<int> BranchId { get; set; }

    public virtual bottle bottle { get; set; }
    public virtual branch branch { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<pay_process> pay_process { get; set; }
}

public partial class branch
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public branch()
    {
        this.bottleOfBranch = new HashSet<bottleOfBranch>();
        this.employee1 = new HashSet<employee>();
        this.invoice = new HashSet<invoice>();
        this.oil_of_branch = new HashSet<oil_of_branch>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> manager { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<bottleOfBranch> bottleOfBranch { get; set; }
    public virtual employee employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<employee> employee1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<invoice> invoice { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<oil_of_branch> oil_of_branch { get; set; }
}

public partial class client
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public client()
    {
        this.invoice = new HashSet<invoice>();
    }

    public int Id { get; set; }
    public string Name_ { get; set; }
    public string phone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<invoice> invoice { get; set; }
}

public partial class employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public employee()
    {
        this.branch = new HashSet<branch>();
        this.invoice = new HashSet<invoice>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string jop_name { get; set; }
    public Nullable<System.DateTime> start_Date { get; set; }
    public Nullable<int> salary { get; set; }
    public Nullable<int> branch_id { get; set; }
    public string password { get; set; }
    public string userName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<branch> branch { get; set; }
    public virtual branch branch1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<invoice> invoice { get; set; }
}

public partial class invoice
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public invoice()
    {
        this.pay_process = new HashSet<pay_process>();
    }

    public int Id { get; set; }
    public Nullable<int> TotaleCash { get; set; }
    public Nullable<System.DateTime> DateInvoice { get; set; }
    public Nullable<int> seller_id { get; set; }
    public Nullable<int> bransh_id { get; set; }
    public Nullable<int> client_id { get; set; }

    public virtual branch branch { get; set; }
    public virtual client client { get; set; }
    public virtual employee employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<pay_process> pay_process { get; set; }
}

public partial class oil
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public oil()
    {
        this.oil_of_branch = new HashSet<oil_of_branch>();
    }

    public int Id { get; set; }
    public string Name_ { get; set; }
    public Nullable<int> price { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<oil_of_branch> oil_of_branch { get; set; }
}

public partial class oil_of_branch
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public oil_of_branch()
    {
        this.pay_process = new HashSet<pay_process>();
    }

    public int Id { get; set; }
    public Nullable<int> id_oil { get; set; }
    public Nullable<int> id_branch { get; set; }
    public Nullable<int> weight { get; set; }

    public virtual branch branch { get; set; }
    public virtual oil oil { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<pay_process> pay_process { get; set; }
}

public partial class pay_process
{
    public int Id { get; set; }
    public Nullable<int> oil_id { get; set; }
    public Nullable<int> Quantity_of_oil { get; set; }
    public Nullable<int> price { get; set; }
    public Nullable<int> invoice_id { get; set; }
    public Nullable<int> bottle_id { get; set; }

    public virtual bottleOfBranch bottleOfBranch { get; set; }
    public virtual invoice invoice { get; set; }
    public virtual oil_of_branch oil_of_branch { get; set; }
}
